---
title: "PEH Data Platform"
description: "Description"
---

## Welcome

This website is the central entry point for documentation, tools, and guidance related to
the **PEH Data Platform**.

It provides access to different documentation sections, each tailored to a specific purpose. 

New sections will be added over time as compomenets become available.

---

## PEH Data Platform

The Personal Exposure and Health (PEH) Data Platform is a secure infrastructure developed and managed by VITO to facilitate the collection, harmonized storage, and controlled access of pseudonymised or anonymised single measurement data from population studies. 

The platform enables Supplying Data Controllers (SDCs) to deposit data, and Receiving Data Controllers (RDCs)
to access approved subsets of PEH data for re-use, in accordance with the terms and conditions of this Protocol 
and all applicable legal and ethical requirements. 

The PEH Data Platform supports transparent data governance, ensures data protection and traceability, and provides operational services for data harmonisation, data processing, quality control, and access management.

In addition to the exchange of single measurement data as governed by this Protocol, the PEH Data Platform also offers additional functionalities, including (but may be not limited to) the collection and publication of metadata and the calculation and publication of summary statistics. 

[https://hbm.vito.be/](https://hbm.vito.be/)


---

## PEH User Documentation

**Stakeholders:** data providers and data users that interact with the PEH Data Platform to provide 

and/or get access to individual leval data

This section contains detailed user guidance to interact with [https://peh.vito.be/](https://peh.vito.be/)

➡️ **Go to:**  
`/peh_userdocumentation/`

---

## Upcoming Sections

The documentation hub is designed to grow. 

Planned additions include:
- ...
- ...
- ...

These sections will appear here once available.

---

## About this documentation

This documentation is developed and maintained by VITO.
It supports transparent, FAIR-compliant access to PEH Data.

