project:
  type: book
  output-dir: ../_site/user-guide

book:
  title: "PEH Data Platform – User Guide"
  downloads: [pdf]

  navbar:
    left:
      - href: ../index.html
        text: About
      - href: ../user-guide/index.html
        text: User guide
      - href: ../pehdata_shiny.html
        text: PEH Data Explorer
    right:
      - icon: github
        href: https://github.com/vito-epi/peh_userdocumentation

  chapters:
    - index.qmd
    - protocol.qmd
    - account.qmd

    - part: "Data Providers"
      chapters:
        - dataproviders/overview.qmd
        - dataproviders/data-requirements.qmd

    - part: "Data Users"
      chapters:
        - datausers/overview.qmd
        - datausers/data-requests.qmd

    - part: "Publications"
      chapters:
        - publications/approved.qmd
        - publications/publications.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false    # ✅ geen nummering op website
    format-links: [pdf]
  pdf:
    toc: true
    number-sections: false    # ✅ geen nummering in PDF