---
title: "Protocol On the management and use of the Personal Exposure and Health Data Platform"
---

The Personal Exposure and Health Data Platform (“PEH Data Platform”) has been developed at VITO in order to
give access and to share single measurement Personal Exposure and Health data (“PEH data”), 
most commonly originating from population studies, in the highest possible resolution to researchers 
and other stakeholders.

It is the intention of the Supplying Data Controllers of the data included in this platform, 
to make the data on this data platform further available to stakeholders according to the terms and conditions
of this protocol and the Regulation 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data (‘GDPR’, General Data Protection Regulation), and allow additional data to be added to it.

This Protocol describes the terms and conditions on the data exchange between Supplying and Receiving Data Controllers via PEH Data Platform, the role of the PEH Data Platform Manager, as well as the processing activities performed by the Receiving Data Controller. 

The can be consulted at [doi.org/10.5281/zenodo.19232226](https://doi.org/10.5281/zenodo.19232226)


To initiate the signature process to sign the Protocol On the management and use of the Personal Exposure and Health Data Platform, send an e-mail to: [PEHDataPlatform@vito.be](mailto:PEHDataPlatform@vito.be)